version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # xml-apis:xml-apis v2, these are older than v1!
      - dependency-name: "xml-apis:xml-apis"
        versions: ["2.0.0", "2.0.2"]
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
        versions: [">=3.0"]
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
        versions: [ ">=3.0" ]